# Generated by Django 3.0.5 on 2024-07-23 13:35

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='product',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='subcategory'),
        ),
    ]
