# Generated by Django 3.0.5 on 2024-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20240723_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='price',
            field=models.IntegerField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
