# Generated by Django 3.0.5 on 2024-07-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_subcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
