# Generated by Django 3.0.5 on 2024-07-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20240724_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
