# Generated by Django 3.0.5 on 2024-07-24 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'InStock'), ('no', 'missing'), ('toOrder', 'after ordering')], default='toOrder', max_length=10)),
            ],
            options={
                'verbose_name': 'InStock',
                'verbose_name_plural': 'InStocks',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.InStock'),
        ),
    ]
