# Generated by Django 3.0.5 on 2024-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20240724_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instock',
            name='status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('toOrder', 'toOrder')], default='toOrder', max_length=10),
        ),
    ]
